# Generated by Django 4.2 on 2023-04-28 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField(default=-1)),
                ('description', models.CharField(default='', max_length=1000)),
                ('catalog', models.IntegerField(default=-1)),
                ('pic', models.CharField(default='', max_length=1000)),
                ('price', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField(default=-1)),
                ('count', models.IntegerField(default=-1)),
                ('worldid', models.IntegerField(default=-1)),
                ('whid', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whid', models.IntegerField(default=-1)),
                ('x', models.IntegerField(default=-1)),
                ('y', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(default=-1, verbose_name='Destination X Value')),
                ('y', models.IntegerField(default=-1, verbose_name='Destination Y Value')),
                ('pkgid', models.IntegerField(default=-1)),
                ('pid', models.IntegerField(default=-1, verbose_name='Product ID')),
                ('count', models.IntegerField(default=-1, verbose_name='Product Count')),
                ('whid', models.IntegerField(default=0)),
                ('truckid', models.IntegerField(default=-1)),
                ('status', models.CharField(blank=True, default='', max_length=100)),
                ('email', models.EmailField(default='default@gmail.com', max_length=254)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
